name: TEST

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    name: "Build: Run tests"
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-
      - name: Gem install
        run:  bundle install
      - name: Pod install
        run: pod install
      - name: Fastlane tests
        run: bundle exec fastlane tests
      - name: Upload XCOV report
        uses: actions/upload-artifact@v1
        with:
          name: XCOV report
          path: xcov_output/
